package com.example.webduck.mock.collection;

import com.example.webduck.collection.domain.CollectionWebtoons;
import com.example.webduck.collection.service.port.CollectionWebtoonsRepository;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeCollectionWebtoonsRepository implements CollectionWebtoonsRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<CollectionWebtoons> data = Collections.synchronizedList(new ArrayList<>());


    public List<CollectionWebtoons> saveAll(List<CollectionWebtoons> collectionWebtoons) {

        return collectionWebtoons.stream().map(webtoon -> {
            CollectionWebtoons savedWebtoon = new CollectionWebtoons(
                autoGeneratedId.incrementAndGet(),
                webtoon.getOwnerId(),
                webtoon.getWebtoonId()
            );
            data.add(savedWebtoon);
            return savedWebtoon;
        }).collect(Collectors.toList());
    }
}
