version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webduck
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy_backend.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/deploy_frontend.sh
      timeout: 180
      runas: ubuntu