spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-secret
            scope: profile,email


secret:
  key: "asdfasdfasdfasdfasdfasdfdasdfasdfadfafdsa"



login:
  redirect:
    url: "localhost:5173"