spring:
  profiles:
    active: dev # prod,dev,test
---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google id
            client-secret: google secret
            scope: profile,email
          kakao:
            client-id: kakao id
            client-secret: kakao secret
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname,profile_image,account_email
          naver:
            client-id: naver id
            client-secret: naver secret
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/DBNAME?allowPublicKeyRetrieval=true&useSSL=false
    username: DBNAME
    password: DBPWD

  jpa:
    hibernate:
      ddl-auto: none
    properties:z
      hibernate:
        format_sql: true
        show_sql: true

