spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 452076268077-4i5s6h332sv3trkl4297a7dfb74e5iql.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            client-id: 3995bb2154a6fc28c4bbc19606e68f09
            client-secret: EQ93LhhvCZHlq4Gge2dSdpvkTCa2Z6lv
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname,profile_image,account_email
          naver:
            client-id: igUQ3mjzqw0u_V7ObSZZ
            client-secret: ZIiuae8Fdg
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: name, email, profile_image, gender, age  # 동의 항목
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/webduck?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true

#logging:
#  level:
#    org:
#      springframework:
#        web: debug

secret:
  key: "b14f7c3f2e4a9d034d9f9c3b15b30a0e3d2b6bca0fa01d8c6f1c66f8a6d376b1"

login:
  redirect:
    url: "http://localhost:5173/oauth2/redirect"

cors:
  origin: "http://localhost:5173"










