name: CI/CD for Main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  S3_BUCKET_NAME: webduck-deploy
  PROJECT_NAME: webduck

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Create application-prod.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > backend/src/main/resources/application-prod.yml
          
      - name: Create .env.production
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" | base64 --decode > frontend/.env.production
          
      - name: Grant execute permission for gradlew
        run: |
          cd backend
          chmod +x gradlew
          
      - name: Build with Gradle
        run: |
          cd backend
          ./gradlew clean build
          
      - name: Make zip file
        run: |
          pwd
          zip -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
          
      - name: Code Deploy
        run: |
          aws deploy create-deployment --application-name webduck-code-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name webduck-code-deploy-group --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
