name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Change directory to backend
      run: cd WebDuck/backend

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Override application.yml for test profile
      run: |
        echo "spring:\n  profiles:\n    active: test" > WebDuck/backend/src/main/resources/application.yml

    - name: Build with Gradle Wrapper
      run: |
        cd WebDuck/backend
        ./gradlew build --no-daemon

    - name: Run tests
      run: |
        cd WebDuck/backend
        ./gradlew test

  dependency-submission:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      run: |
        cd WebDuck/backend
        ./gradlew dependencies --no-daemon
