name: Java CI with Gradle and AWS Deployment

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: |
        cd backend
        ./gradlew build --no-daemon

    - name: Configure AWS Credentials
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: aws-region: ap-northeast-2

    - name: Upload to S3
      run: |
        aws s3 cp --region ap-northeast-2 ./build.zip s3://webduck-bucket/build.zip
    - name: Deploy
      run: aws deploy create-deployment
        --application-name webduck-code-deploy 
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name webduck-code-deploy-group
        --s3-location bucket=webduck-bucket,bundleType=zip,key=build.zip




  dependency-submission:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Change directory to backend and Generate and submit dependency graph
      run: |
        cd backend
        ./gradlew dependencies --no-daemon
