name: Java CI with Gradle

on:
  push:
    branches: 
        - 'main'
        - 'dev'
  pull_request:
    branches: 
        - 'main'
        - 'dev'
env: 
  S3_BUCKET_NAME: webudck-deploy
  PROJECT_NAME: playground-logging # 이 부분 의아함
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: |
        cd backend
        chmod +x gradlew
        
    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew clean build

    - name: Make zip file
      run: zip ./$GITHUB_SHA.zip .
      shell: bash
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip