name: Java CI with Gradle and AWS Deployment

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: |
        cd backend
        ./gradlew build --no-daemon

    - name: Configure AWS Credentials
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # 수정됨: aws-region: aws-region: ap-northeast-2 에서 aws-region: ap-northeast-2

    - name: Zip the build
      run: |
        cd backend/build/libs/
        zip -r build.zip .
    
    - name: Upload to S3
      run: |
        aws s3 cp build.zip s3://webduck-bucket/build.zip # 수정됨: --region 옵션 제거 및 경로 수정

    - name: Deploy to AWS CodeDeploy
      run: |
        aws deploy create-deployment --application-name webduck-code-deploy --s3-location bucket=webduck-bucket,key=build.zip,bundleType=zip --deployment-group-name webduck-code-deploy-group --deployment-config-name CodeDeployDefault.AllAtOnce --region ap-northeast-2 # 수정됨: 명령어 형식 수정

  dependency-submission:
    runs-on: ubuntu-latest
    needs: build-and-deploy # 수정됨: needs: build에서 needs: build-and-deploy로 변경
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Change directory to backend and Generate and submit dependency graph
      run: |
        cd backend
        ./gradlew dependencies --no-daemon
